### PR TITLE
mobile menu keyboard accessible and fix for hover state

### PR DESCRIPTION
**Pull request by mandy-kate**
Hi @ebuckley 

This PR is to replicate changes made to the header on CWP site 

- Mobile navigation keyboard accessible 
- custom js that checks if menu is collapsed or not and applies appropriate css 
- Fix for hover state in mobile nav

Before reviewing can you please deploy this branch to UAT so I can test? 

Thanks!
Amanda

@ebuckley could you please add me to your media suite slack channel if you think that might help (mandykatebaker@gmail.com)

### CODE REVIEW

**Comment by ebuckley** [comment]
Thanks for the PR Mandy, this branch is deployed here currently https://test.uat.data.govt.nz/dataset

test.uat is the ckan 2.7 instance so I've rebased these changes on #9 . The temporary branch for testing these out is here https://github.com/data-govt-nz/ckanext-dia_theme/tree/temp/2.7-mobile-theme-testing

**Comment by camfindlay** [comment]
@mandy-kate can you confirm that this is as expected on the test site url above?

**Comment by camfindlay** [comment]
Ive viewed and it looks to work as expected. @ebuckley this will need a CKAN 2.6 deploy.

**Comment by mandy-kate** [comment]
@ebuckley apologies yes I tested on uat and all working as expected (apologies for delay)

**Pull request merged**
